### ISSUE TITLE
Pie Chart don´t show values bellow  1.0% 

### ISSUE THREAD

**Issue by victortdc** [apgapg/pie_chart#49] opened 2020-08-27 18:30 UTC
![Issue](https://user-images.githubusercontent.com/63310837/91480926-0671d900-e87a-11ea-97f9-fae65d3d6cbc.png)
Sometimes happens that PieChart "cut" the values under 1.0%

**Comment by apgapg** [comment] 2020-09-05 04:41
Duplicate of #33

**Closed by apgapg** 2020-09-05 04:41 UTC
